FROM ghcr.io/apollographql/router:v2.0.0-preview.0

COPY router-prod.yaml /config.yaml

ENV APOLLO_ROUTER_LISTEN_ADDRESS=0.0.0.0:4000

# Expose the port that the router will run on
EXPOSE 4000

CMD ["--config", "/config.yaml"]