FROM ghcr.io/apollographql/router:v2.0.0-preview.0

COPY router-prod.yaml /config.yaml

# Expose the port that the router will run on
EXPOSE 4000

# Set environment variables for Cloud Run
ENV PORT=4000

CMD ["--config", "/config.yaml"]